"main" should not "throw" anything
Why is this an issue? There’s no reason for a main method to throw anything. After all, what’s going to catch it? Instead, the method should itself gracefully handle any exceptions that may bubble up to it, attach as much contextual information as possible, and perform whatever logging or user communication is necessary, and exit with a non-zero (i.e. non-success) exit code if necessary. 
### Noncompliant
{{BUGGY}}
### Compliant
