Exception testing via JUnit ExpectedException rule should not be mixed with other assertions
Why is this an issue? When testing exception via org.junit.rules.ExpectedException any code after the raised exception will not be executed, so adding subsequent assertions is wrong and misleading. This rule raises an issue when an assertion is done after the "expect(…)" invocation, only the code throwing the expected exception should be after "expect(…)". You should consider using org.junit.Assert.assertThrows instead, it’s available since JUnit 4.13 and it allows additional subsequent assertions. Alternatively, you could use try-catch idiom for JUnit version < 4.13 or if your project does not support lambdas. 
### Noncompliant
{{BUGGY}}
### Compliant
