Exceptions should not be thrown in finally blocks
Throwing an exception from within a finally block will mask any exception which was previously thrown in the try or catch block, and the maskedâ€™s exception message and stack trace will be lost. 
### Noncompliant
{{BUGGY}}
### Compliant
